### ISSUE TITLE
Login does not work occasionally

### ISSUE THREAD

**Issue by lthueer** [liqd/zt-app#231]
**URL:** 
**user:** 
**expected behaviour:** log in works properly
**behaviour:** log in sometimes work, sometimes not
**important screensize:**
**device & browser:** Google Pixel 4a (Android 12), Lenovo Yoga Tab 3 (Android 11)
**Comment/Question:** 
Error message: "An error occured - Unable to log in with provided credentials". Using a+ dev credentials of all kinds

**Comment by Rineee** [comment]
@lthueer So I understand it right, that it sometimes works and sometimes doesn't on the same device and same account?

**Comment by lthueer** [comment]
@Rineee exactly! After trying it for a while (closing and opening the app again) it finally worked using the same account. On another device I didn't manage to log in at all and the error message always pops up. This is weird :/

**Comment by Rineee** [comment]
@lthueer And once you are logged in everything works fine? Hm, that is weird, it sound more like a setup problem to me..  @khamui @goapunk Do you have any ideas on that?

**Comment by khamui** [comment]
Just guessing here, but maybe it was related with the api url thingy, which is solved and merged after this issue report?

https://github.com/liqd/zt-app/pull/230

@lthueer can you test again to login?

**Comment by lthueer** [comment]
@khamui @Rineee it's still the same for me! Maybe related to #232 ?

**Comment by Rineee** [comment]
@lthueer Yes, maybe.. but here you tested on Android, right?

**Comment by lthueer** [comment]
@Rineee yes!

**Comment by goapunk** [comment]
Sounds like #230 might be cause, maybe in a combination with #232 because it did work for me when testing. Will try to investigate.

**Comment by lthueer** [comment]
@khamui @Rineee The problem occurred due to the different QR codes in our wiki. @goapunk will update them!
Cheers

**Comment by Rineee** [comment]
> @khamui @Rineee The problem occurred due to the different QR codes in our wiki. @goapunk will update them! Cheers

Nice!
