### ISSUE TITLE
#6233: Iphone 11 profile view doesnot show fully settings symbol & back button | profile settings not working

### ISSUE THREAD

**Issue by lthueer** [liqd/zt-app#390]
**URL:** 
**user:** 
**expected behaviour:** back button and settings symbol are clickable
**behaviour:** back button and settings symbol are not fully there
**important screensize:**
**device & browser:** tested on Iphone 11 pro
**Comment/Question:** 

It looks like the two buttons are too high, so you can't see them. On ios you can just see the edge of the symbols
Only on ios. On Iphone 6s it works fine

Update (08.08.22)
IOS, Iphone 12 pro

1) 
![IMG_20220808_144237_038](https://user-images.githubusercontent.com/36957474/183420915-0f52e727-8fc8-4647-9804-539d85c47767.jpg)

2)
![IMG_20220808_144244_432](https://user-images.githubusercontent.com/36957474/183420889-b495edf8-1734-47fb-b901-b6b11294207c.jpg)

**Comment by phillimorland** [comment]
@luca I refactored when doing the rest of the profile so it will hopefully be fixed when that is merged

**Comment by lthueer** [comment]
@phillimorland ok, cool. I've thought you would have that in mind!

**Comment by goapunk** [comment]
should be fixed now!

**Comment by lthueer** [comment]
@phillimorland @goapunk this issue is still there for ios. Tested it on iphone 11 pro. The buttons are too high on top of the screen and the profile settings look off (see second screenshot)

**Comment by goapunk** [comment]
hmm, I guess that's the first device which has a big notch. Guess we'll have to test on that specific device

**Comment by phillimorland** [comment]
@goapunk @lthueer the screen should look totally different now, is the version on dev correct?

**Comment by lthueer** [comment]
@phillimorland the iphone 11 pro is in the office, maybe you can have a look at it when you're there? Otherwise I can check it on Thursday

**Comment by phillimorland** [comment]
seems to be fixed now
